name: txtx
summary: A Smart Contract Runbook execution tool
description: |
  ```diff
  $ txtx --tldr
  
  ! Build Confidence with Smart Contract Runbooks
  
  # Secure by design
  - Copy/pasted private keys for operations and deployments leading to security breaches.
  + Keep your private keys where they are - Hardware wallet, Web wallet, Secure enclaves.
  
  # Clarity in your operations and deployments
  - Bloated, hacky Javascript code synchronizing sequences of transactions. 
  + Simple and declarative code, focused on what to do (vs how to do it).
  ```
  ## About Txtx
  Txtx enhances the blockchain development experience by introducing the concept of Smart Contract Runbooks. 
  These runbooks serve as detailed guides to ensure that interactions with the blockchain, such as contract deployments and calls, are consistent and reliable. 
  Written in declarative languages like JSON or YAML, Smart Contract Runbooks describe the necessary transactions for deploying or interacting with smart contracts in a chain-agnostic manner. 
  This approach not only promotes standardization and composability but also enhances explainability, making the developer's job more straightforward and efficient.

  By utilizing Txtx, developers can leverage these runbooks to create reproducible workflows, which are essential for maintaining robustness in blockchain operations. 
  The Txtx toolchain also includes a dashboard that aids in the execution and monitoring of these runbooks, providing a comprehensive solution for web3 developers. 
  This innovation addresses the current gaps in web3 developer tooling, such as the lack of standardization and composability, and paves the way for more efficient and collaborative blockchain development.
version: 'v0.2.6'

base: core22
confinement: strict

parts:
  txtx-install:
    source: https://github.com/txtx/txtx/releases/download/v0.2.6/txtx-linux-x64.tar.gz
    plugin: dump
    source-type: tar
    organize: 
      txtx-linux-x64/txtx: usr/local/bin/txtx

apps:
  txtx:
    command: txtx
    plugs:
     - network
     - network-bind
     - mount-observe
     - home
     - desktop